Rabbit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls', namespace='item')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [ 
    path('', views.IndexView.as_view(), name='home'),
    path('aboutus/', views.About.as_view(), name='about'),
    path('services/', views.Services.as_view(), name='service'),
    path('service/detail/<int:pk>/', views.ServicesDetail.as_view(), name='service-detail'),
    path('product/', views.ProductPage.as_view(), name='product'),
    path('product/category/<int:pk>', views.ProductCategory.as_view(), name='product-category'),
    path('product/detail/<int:pk>', views.ProductDetails.as_view(), name='product-detail'),
    path('gallery/', views.GalleryPage.as_view(), name='gallery'),
    path('gallery/category/<int:pk>', views.GalleryCategoryView.as_view(), name='gallery-category'),
    path('shop/', views.Shop.as_view(), name='shop'),
    path('blog/', views.BlogPage.as_view(), name='blog'),
    path('blog/detail/<int:pk>/', views.BlogDetail.as_view(), name='blog-detail'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('recipe/', views.RecipePage.as_view(), name='recipe'),
    path('recipe/detail/<int:pk>', views.RecipeDetail.as_view(), name='recipe-detail'),
    path('faq/', views.FaqPage.as_view(), name='faq'),
    path('tour/detail/<int:pk>', views.TourDetail.as_view(), name='tour-detail'),
]

item/forms.py
from django import forms
from item.models import Message, OrderInfo

class ContactForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['full_name', 'email', 'phone_number', 'address', 'message']

class ShopForm(forms.ModelForm):
    class Meta:
        model = OrderInfo
        fields = ['product_name', 'email', 'phone_number', 'quantity', 'address', 'note']

item/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView
from . forms import ContactForm, ShopForm
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from . models import CompanyDetail, CompanyIntroduction, AboutUs, WhatWeDo, Partnership, AwardList, Testimonial, Service, ServiceDetail, Event, Package, PackageService, Gallery, Category, CategoryDetail, CompanyDetail, Message, OrderInfo, Recipe, Question, QuestionCategory, Blog, Program, Offer, WorkTogether, WorkFor, Stories, ProductDetail, ProductSubImage, Tour, TourDetailItinerary, IncludedCost, GalleryCategory

# Create your views here.
class IndexView(TemplateView):
    template_name = 'item/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company_detail'] = CompanyDetail.objects.last()
        context['company_intro'] = CompanyIntroduction.objects.last()
        context['recent'] = Blog.objects.all().order_by('-date')[:3]
        context['program'] = Program.objects.all()
        context['offer'] = Offer.objects.all()[:3]
        context['work_together'] = WorkTogether.objects.last()
        context['work_for'] = WorkFor.objects.all()
        context['story'] = Stories.objects.all()
        return context

class About(TemplateView):
    template_name = 'item/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = AboutUs.objects.last()
        context['we_do'] = WhatWeDo.objects.all()
        context['partner'] = Partnership.objects.all()
        context['award'] = AwardList.objects.all()
        context['testimonial'] = Testimonial.objects.all()
        return context
   

class Services(TemplateView):
    template_name = 'item/services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service'] = Service.objects.all()
        context['package'] = Package.objects.filter(service_id__isnull=True)
        context['tour'] = Tour.objects.all()
        return context

class ServicesDetail(DetailView):
    model = Service
    template_name = 'item/service-detail.html'
    context_object_name = 'detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service_detail'] = ServiceDetail.objects.filter(service__id=self.kwargs.get("pk"))
        context['event'] = Event.objects.filter(service_id=self.kwargs.get("pk"))
        context['package'] = Package.objects.filter(service_id=self.kwargs.get("pk"))
        return context
    
    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Service, pk=id_)

class ProductPage(ListView):
    template_name = 'item/product.html'
    model = CategoryDetail
    paginate_by = 4
    context_object_name = "list"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all().order_by('name')
        if categories: 
            context['category'] = categories
        return context
    
    def get_queryset(self, **kwargs):
        categories = Category.objects.all().order_by('name')
        if categories:
            return CategoryDetail.objects.filter(category_id=categories[0].id)
        else:
            return []


class ProductDetails(DetailView):
    model = CategoryDetail
    template_name = 'item/product_detail.html'
    context_object_name = 'detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = CategoryDetail.objects.get(id=self.kwargs.get("pk"))
        return context

class ProductCategory(ListView):
    template_name = 'item/product.html'
    model = CategoryDetail
    paginate_by = 4
    context_object_name = "list"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all().order_by('name')
        context['category'] = categories
        return context
    
    def get_queryset(self, **kwargs):
        return CategoryDetail.objects.filter(category_id=self.kwargs.get("pk"))
    

# class GalleryPage(TemplateView):
#     template_name = 'item/gallery.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['gallery'] = Gallery.objects.all()
#         context['cat'] = GalleryCategory.objects.all()
#         return context

class GalleryPage(ListView):
    template_name = 'item/gallery.html'
    model = GalleryCategory
    context_object_name = "list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = GalleryCategory.objects.all().order_by('name')
        if categories: 
            context['category'] = categories
        return context

    def get_queryset(self, **kwargs):
        categories = GalleryCategory.objects.all().order_by('name')
        if categories:
            return Gallery.objects.filter(category_id=categories[0].id)
        else:
            return []
    


class GalleryCategoryView(ListView):
    template_name = 'item/gallery.html'
    model = Gallery
    context_object_name = "cat"

    def get_queryset(self, **kwargs):
        return Gallery.objects.filter(category_id=self.kwargs.get("pk"))





class Shop(TemplateView):
    template_name = 'item/shop.html'
    model = OrderInfo
    form_class = ShopForm

    def post(self, request, *args, **kwargs):
        product_name = request.POST.get('product_name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        quantity = request.POST.get('quantity')
        address = request.POST.get('address')
        note = request.POST.get('note')

        success = OrderInfo.objects.create(product_name=product_name,  email=email, phone_number=phone_number, quantity=quantity, address=address,  note=note)

        return HttpResponseRedirect('/') 

class BlogPage(ListView):
    template_name = 'item/blog.html'
    model = Blog
    paginate_by = 4
    context_object_name = "list"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent'] = Blog.objects.all().order_by('-date')[:4]
        return context
    
    def get_queryset(self):
        return Blog.objects.all()

class BlogDetail(DetailView):
    template_name = 'item/blog-detail.html'
    model = Blog
    context_object_name = 'blog_info'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = Blog.objects.first()
        context['recent'] = Blog.objects.all().order_by('-date')[:4]
        return context

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Blog, pk=id_)

class Contact(TemplateView):
    template_name = 'item/contact-us.html'
    model = Message
    form_class = ContactForm

    def get_context_data(sel, **kwargs):
        context = super().get_context_data(**kwargs)
        context['info'] = CompanyDetail.objects.first()
        return context

    def post(self, request, *args, **kwargs):
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        address = request.POST.get('address')
        message = request.POST.get('message')

        success = Message.objects.create(full_name=full_name,  email=email, phone_number=phone_number, address=address,  message=message)

        return HttpResponseRedirect('/')

class RecipePage(ListView):
    template_name = 'item/recipes.html'
    model = Recipe
    context_object_name = 'recipe'
    paginate_by = 4

class RecipeDetail(DetailView):
    template_name = 'item/recipes-detail.html'
    model = Recipe
    context_object_name = 'recipe_info'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipe'] = Recipe.objects.first()
        return context

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Recipe, pk=id_)

class FaqPage(TemplateView):
    template_name = 'item/faq.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = QuestionCategory.objects.all()
        return context
    
    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Question, pk=id_)

class TourDetail(DetailView):
    template_name = 'item/tour-detail.html'
    model = Tour
    context_object_name = 'tour'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tour_det'] = TourDetailItinerary.objects.filter(tour_id=self.kwargs.get("pk"))
        context['tour_cost'] = IncludedCost.objects.filter(tour_id=self.kwargs.get("pk"))
        return context


    

item/templates/item/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Rabbit</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/plugins.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<header class="main__header">
		<div class="container">
			<div class="row">
				<nav class="navbar navbar-expand-lg navbar-light">
				  <a class="navbar-brand sitemain__logo" href="{% url 'item:home' %}">
				  	<img src="{% static 'images/logo.png' %}" alt="rabbit logo">
				  </a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>

				  <div class="collapse navbar-collapse" id="navbarSupportedContent">
				    <ul class="navbar-nav ml-auto">
				      <li class="nav-item" id="home">
				        <a class="nav-link" href="{% url 'item:home' %}">Home</a>
				      </li>
				      <li class="nav-item" id="about">
				        <a class="nav-link" href="{% url 'item:about' %}">About us</a>
				      </li>
				      <li class="nav-item" id="service">
				        <a class="nav-link" href="{% url 'item:service' %}">Services</a></a>
                      </li>
                      <li class="nav-item" id="product">
				        <a class="nav-link" href="{% url 'item:product' %}">Product</a></a>
                      </li>
                      <li class="nav-item" id="recipe">
				        <a class="nav-link" href="{% url 'item:recipe' %}">Recipe</a></a>
				      </li>
                      <li class="nav-item" id="gallery">
				        <a class="nav-link" href="{% url 'item:gallery' %}">Gallery</a></a>
				      </li>
				      <li class="nav-item" id="shop">
				        <a class="nav-link" href="{% url 'item:shop' %}">Shop</a>
				      </li>
				      <li class="nav-item" id="blog">
				        <a class="nav-link" href="{% url 'item:blog' %}">Blog</a>
                      </li>
                      <li class="nav-item" id="faq">
				        <a class="nav-link" href="{% url 'item:faq' %}">FAQ</a>
				      </li>
				      <li class="nav-item" id="contact">
				        <a class="nav-link" href="{% url 'item:contact' %}">Contact us</a>
				      </li>
				    </ul>
				  </div>
				</nav>
			</div>
		</div>
    </header>
{% block content %}
{% endblock %}
<footer class="main__footer pd__btm__tp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="foot__component__wrapper">
                    <div class="foot__comp__oveview">
                        <div class="foot__comp__ov_txt">
                            <p>We bring the power of ownership to your organization <br/>by aligning strategy and culture.</p>
                        </div>
                    </div>
                    <div class="foot__menulinks">
                        <span class="foot__menuttl">
                            Contact Info
                        </span>
                        <div class="foot__cont__info">
                            <p>{{ info.location }}</p>
                            <br/>
                            <p>{{ info.contact_number }}<br/>{{ info.email }}</p>

                        </div>
                        <div class="social__links">
                            <span class="link__head">Follow Us:</span>
                            <ul>
                                <a href="{{ info.facebook_url }}"><li><i class="fa fa-facebook" aria-hidden="true"></i></li></a>
                                <a href="{{ info.instagram_url }}"><li><i class="fa fa-instagram" aria-hidden="true"></i></li></a>
                                <a href="{{ info.gmail_url }}"><li><i class="fa fa-google" aria-hidden="true"></i></li></a>
                                <a href="{{ info.twitter_url }}"><li><i class="fa fa-twitter" aria-hidden="true"></i></li></a>
                                <a href="{{ info.youtube_url }}"><li><i class="fa fa-youtube" aria-hidden="true"></i></li></a>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 mb-3">
                <div class="foot__menulinks">
                    <span class="foot__menuttl foot__nav__head">
                        Resources
                    </span>
                    <ul>
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#"> About us</a>
                        </li>
                        <li>
                            <a href="#">Services</a>
                        </li>
                        <li>
                            <a href="#">Services</a>
                        </li>
                        <li>
                            <a href="#">Product</a>
                        </li>
                        <li>
                            <a href="#">Recipe</a>
                        </li>
                        <li>
                            <a href="#">FAQ</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- <div class="col-lg-3 mb-3">
                <div class="foot__menulinks">
                    <span class="foot__menuttl foot__nav__head">
                        Resources
                    </span>
                    <ul>
                        <li>
                            <a href="#">News & Events</a>
                        </li>
                        <li>
                            <a href="#">Media Coverage</a>
                        </li>
                        <li>
                            <a href="#">Events/Campaign</a>
                        </li>
                        <li>
                            <a href="#">National Recipes</a>
                        </li>
                        <li>
                            <a href="#">InterNational Recipes</a>
                        </li>
                        <li>
                            <a href="#">Videos</a>
                        </li>
                        <li>
                            <a href="#">FAQs</a>
                        </li>
                    </ul>
                </div>
            </div> -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="copy__foot">
                    <p>Copyright 2019 The Himalayan Rabbit Farm. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'js/jquery_min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/masonry.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}
{% endblock %}

item/templates/item/blog-detail.html
{% extends 'item/base.html' %}
{% load static %}
{% block content %}
<section class="detail__news_and__blog pd__btm__tp">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="blog__thumb__and__content">
					<div class="blog__detail__img">
						<img src="{{ blog_info.image.url }}" alt="">
					</div>
					<div class="blog__detail__content__container">
						<div class="detail__blog__news__release__date">
							<span class="published__year__time__blog">Publish on: {{ blog_info.date }}</span>
							
						</div>
						<div class="news__detail__parag">
							<h5>{{ blog_info.title }}</h5>
							<p>{{ blog_info.description|linebreaks }}</p>

						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="recent__post__abt__rabt">
					<div class="blgs__sidebar">
						<h6>Recent Post</h6>
					</div>
					<div class="wrapper__post__blog">
						<ul>
							{% for item in recent %}
							<li>
								<a href="{% url 'item:blog-detail' item.pk %}">
									<div class="news__sidebar__post">
										<img src="{{ item.image.url }}" alt="">
									</div>
									<div class="post__content__sidebar">
										
										<h6>{{ item.title }}</h6>
										<div class="news__post__date">
											<span>Published on: {{ item.date }}</span>
										</div>
									</div>
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

item/templates/item/faq.html
{% extends 'item/base.html' %}
{% load static %}
{% block content %}
<section class="feq__asked__que">
	<div class="container">
		<div class="row">
			{% for item in category %}
			<div class="col-md-12">
				<div class="top__bgr__banner__srvs">
					<div class="top__bgr__banner__srvs__content">
						<img src="{{ item.image.url }}" alt="">
						<div class="faq__ban__txt text-center">
							<div class="section__heading wht__heading no__padding__heading">
								<h1>{{ item.name }}</h1>
							</div>
							<div class="serv_ban_para">
								<p>{{ item.description|linebreaks }}</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-9 mx-auto frequently__ask__qans">
					<div id="accordion">
						{% for obj in item.quecat.all %}
					    <div class="card">
					      <div class="card-header">
					      <a class="card-link faq__question" data-toggle="collapse" href="#ques{{ obj.id }}">
					      	<span>{{ forloop.counter }}</span>
					      	 {{ obj.question }}
					        </a>
					      </div>
					      <div id="ques{{ obj.id }}" class="collapse" data-parent="#accordion">
					        <div class="card-body">
					          {{ obj.answer }}
					        </div>
					      </div>
						</div>
						{% endfor %}
					</div>
   					</div>
				</div>
				{% endfor %}
			</div>
			
		</div>
</section>
{% endblock %}
{% block scripts %}
	<script>
		$("#faq").addClass('active');
	</script>
{% endblock %}

item/templates/item/product.html
{% extends 'item/base.html' %}
{% load static %}
{% block content %}
<section class="rabbit__recipes pd__btm__tp">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 mx-auto">
			        <div class="section__heading text-center recipies__content__abt__rabbit">
			            <h2>Buy anything related to rabbit</h2>
			            <p>Online learning offers a new way to explore subjects you’re passionate about.</p>
		            	<p>Find your interests by browsing our online course categories:</p>

		            	<div class="anything__relt__to__rabbit">
							{% if category %}
							
							{% for item in category %}
						
		            		<div class="shp-det-lnk">
		            			<a href="{% url 'item:product-category' item.pk %}">{{ item.name }}</a>
							</div>
						
							{% endfor %}
							{% endif %}
							
		            	</div>
			        </div>
			    </div>
		</div>
	</div>
</section>
<section class="recipes__and__thumb__rabbit pd__btm">
	<div class="container">
		<div class="row recipes__pd-btm">
			{% if list %}
			{% for item in list %}
			<div class="col-lg-3 col-md-6 mb-4">
				    <div class="blog__listshm__holder recipies__border__wrapper">
				        <div class="blog__listshm">
				            <div class="blog__thum">
				                <a href="{% url 'item:product-detail' item.pk %}">
				                    <img src="{{ item.image.url }}" alt="">
				                </a>
				            </div>
				            <div class="blog__meta__desc recipes__content__items__box">
				                <div class="blog__desc recipes__wrapper__box">
				                    <div class="blog__desc__cont">
				                        <h3><a href="{% url 'item:product-detail' item.pk %}">{{ item.title }}</a></h3>
				                        <p>{{ item.description|truncatechars:100 }}</p>

				                        <div class="rabbit__type__and__price">
											{% if item.gender %}
											<span>{{ item.gender }}</span>
											{% endif %}
					                    	<span class="prc__per__piece">Rs.<strong>{{ item.price }}</strong> per {{ item.unit }}</span>
				                   		 </div>
				                    </div>
				                    <div class="blog__detail__link recipes__content__view__detail__btn">
				                        <a href="{% url 'item:product-detail' item.pk %}" class="view__detail__recipes">View Details </a>
				                    </div>
				                </div>
				            </div>
				        </div>
				    </div>
			</div>
		
			{% endfor %}
			{% endif %}
		</div>
		<div class="row recipes__pd-btm-top">
			{% if list %}
			{% if is_paginated %}
			<div class="col-md-12">
				<div class="bottom__pagination ">
					<ul class="pagination">
						{% if page_obj.has_previous %}
						<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
						{% endif %}
						{% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
							<li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
							{% else %}
							<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
							{% endif %}
						{% endfor %}
						{% if page_obj.has_next %}
						<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
						{% endif %}
					  </ul>
				</div>
			</div>
			{% endif %}
			{% endif %}
		</div>
</section>
{% endblock %}
{% block scripts %}
	<script>
		$("#product").addClass('active');
	</script>
{% endblock %}

item/templates/item/services.html
{% extends 'item/base.html' %}
{% load static %}
{% block content %}
<section class="rabbit__services pd__btm__tp">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 mx-auto">
			        <div class="rabbit__service__content text-center text-white">
			            <h2>Explore our services</h2>
			            <p>Online learning offers a new way to explore subjects you’re passionate about.</br>
							Find your interests by browsing our online course categories:</p>
						<div class="packages__btn">
		            			<a href="#packages">View our packages</a>
		            	</div>
			        </div>
			    </div>
		</div>
	</div>
</section>
<section class="what__we__serve pd__btm__tp">
		<div class="container">
			<div class="row">
				<div class="col-lg-7 mx-auto text-center">
					<div class="packages__we__serve__content">
						<h2>What we serve</h2>
						<div class="contain__about__we__do">
							<p>Online learning offers a new way to explore subjects you’re passionate about.</p>
							<p>Find your interests by browsing our online course categories:</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row align-items-center">
				{% for item in service %}
				<div class="col-md-4 mb-3">
					
					<div class="rabbit__service__type">
						<div class="service__icon__type">
						   <div class="rabit__srvs__img">	
						   	  <img src="{{ item.image.url }}" alt="">	
						   </div>
						  <h6>{{ item.title }}</h6>
						</div>
						<div class="service__content">
							<p>
								{{ item.description }}
							</p>
						</div>
						<div class="service__more__detail">
							<a href="{% url 'item:service-detail' item.pk %}">More in detail</a>
						</div>
					</div>
					
				</div>
				{% endfor %}
			</div>			
		</div>
</section>
<section class="what__we__serve pd__btm__tp">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 mx-auto text-center mb-3">
				<div class="packages__we__serve__content">
					<h2>Our Tour</h2>
					<div class="contain__about__we__do">
						<p>Online learning offers a new way to explore subjects you’re passionate about.<br>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row align-items-center">
			<div class="col-md-12">
				{% for item in tour %}
				<div class="tour__package mb-3">
					<div class="tour img__thumb__package">
						<img src="{{ item.image.url }}" alt="">
					</div>
					<div class=" tour package__tour__content">
						<div class="content__mid">	
								<h6>{{ item.name }}</h6>
								<p>{{ item.overview }}</p>
							</div>
							<div class="tour view__detail__packages__in_tour">
								<div class="price__per_per">
									<span>Rs.<strong>{{ item.price }}</strong></span>
									<!-- <span>Per Person</span> -->
								</div>
							<div class="package__tour__detail">
								<a href="{% url 'item:tour-detail' item.pk %}">View More</a>
							</div>
						</div>
					</div>					
				</div>
				{% endfor %}
				<!-- <div class="tour__package mb-3">
					<div class="tour img__thumb__package">
						<img src="{% static 'images/blog01.jpg' %}" alt="">
					</div>
					<div class=" tour package__tour__content">
						<div class="content__mid">	
								<h6>Grand Hotel - Non Casino</h6>
								<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam maiores officiis repellat ea consequuntur praesentium placeat pariatur voluptate nobis modi?</p>
							</div>
							<div class="tour view__detail__packages__in_tour">
								<div class="price__per_per">
									<span>Rs.<strong>22,343</strong></span>
									<span>Per Person</span>
								</div>
							<div class="package__tour__detail">
								<a href="#">View More</a>
							</div>
						</div>
					</div>					
				</div> -->
			</div>
		</div>			
	</div>
</section>
<section class="rabbit__available__packages pd__btm__tp">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 mx-auto">
			        <div class="packages__for__rbt text-center">
			            <h2>Explore our services</h2>
			            <p>Online learning offers a new way to explore subjects you’re passionate about.</p>
			            	<p>Find your interests by browsing our online course categories:</p>
			        </div>
			    </div>
		</div>
		<div class="row packages__plan__pd" id="packages">
			{% for item in package %}
			<div class="col-md-4 mb-4 rab__resp__packages">
				<div class="plans__and__enquery">
					<div class="package__plan__numb">
						<span>{{ forloop.counter }}</span>
					</div>
					<div class="plan__and__rupes">
						<h5>{{ item.package_name }} / <span>{{ item.price }}</span></h5>
					</div>
					<div class="types__of__package__plan">
						<ul>
							{% for obj in item.package.all %}
							<li><span><i class="fa fa-check-square" aria-hidden="true"></i></span>{{ obj.service }}</li>
							{% endfor %}
						</ul>
					</div>
					<div class="plan__type__btn">
						<a href="#">Enquery Now</a>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</section>
{% endblock %}
{% block scripts %}
	<script>
		$("#service").addClass('active');
	</script>
{% endblock %}